version: "3.9"
services:
  app:
    image: teamavail:latest
    container_name: availability-tracker
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:8080"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: availability-redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis_volume:/data"
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

