version: "3.9"

services:
  app:
    image: teamavail:latest
    container_name: availability-tracker
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
       - "/var/jenkins_home/workspace/Availability_Tracker/input:/app/input:rw"
       - "/var/jenkins_home/workspace/Availability_Tracker/output:/app/output:rw"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: availability-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_volume:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

  history-sync:
    image: redis:7-alpine
    container_name: availability-history-sync
    depends_on:
      - app
      - redis
    volumes:
      - ./output:/app/output
    entrypoint: ["sh", "-c"]
    command: >
      "mkdir -p /app/output; \
      sleep 2; \
      r=\$(redis-cli -h redis -p 6379 GET history); \
      if [ -n \"$r\" ]; then \
        printf \"%s\" \"$r\" > /app/output/history.json; \
      else \
        if [ -f /app/output/history.json ]; then \
          cat /app/output/history.json | redis-cli -h redis -p 6379 -x SET history >/dev/null; \
        fi; \
      fi; \
      prev_r=\"\$(printf %s \"$r\" | sha256sum | awk '{print $1}')\"; \
      if [ -f /app/output/history.json ]; then \
        prev_f=\"\$(sha256sum /app/output/history.json | awk '{print $1}')\"; \
      else \
        prev_f=\"\"; \
      fi; \
      while :; do \
        r=\$(redis-cli -h redis -p 6379 GET history); \
        rh=\"\$(printf %s \"$r\" | sha256sum | awk '{print $1}')\"; \
        if [ -n \"$r\" ] && [ \"$rh\" != \"$prev_r\" ]; then \
          printf \"%s\" \"$r\" > /app/output/history.json; \
          prev_r=\"$rh\"; \
          prev_f=\"\$(sha256sum /app/output/history.json | awk '{print $1}')\"; \
        fi; \
        if [ -f /app/output/history.json ]; then \
          fh=\"\$(sha256sum /app/output/history.json | awk '{print $1}')\"; \
          if [ \"$fh\" != \"$prev_f\" ]; then \
            cat /app/output/history.json | redis-cli -h redis -p 6379 -x SET history >/dev/null; \
            prev_f=\"$fh\"; \
            prev_r=\"\$(printf %s \"\$(cat /app/output/history.json)\" | sha256sum | awk '{print $1}')\"; \
          fi; \
        fi; \
        sleep 2; \
      done"
    restart: unless-stopped

volumes:
  redis-data:

